yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
Group = 'Group'


class Post(models.Model):
    """Модель для хранения постов"""

    text = models.TextField(verbose_name='Description')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Date of publication')
    author = models.TextField(verbose_name='Author')
    group = models.ForeignKey(
        Group,
        related_name='posts',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )

    class Meta:
        verbose_name = 'Alex Posting'
        verbose_name_plural = 'Alex Postings'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text


class Group(models.Model):
    """Модель для тематических сообществ пользователей """

    title = models.CharField(max_length=200, verbose_name='Title')
    slug = models.SlugField(unique=True, verbose_name='Slug')
    description = models.TextField(verbose_name='Description')

    class Meta:
        verbose_name = 'Alex Group'
        verbose_name_plural = 'Alex Groups'

    def __str__(self) -> str:
        return self.title

yatube/posts/forms.py
from django import forms

from .models import Post


class FormPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        label = {
            'text': ('Текст поста'),
            'group': ('Группа поста')
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import FormPost
from .models import Group, Post, User


def index(request):
    posts_list = Post.objects.all()
    paginator = Paginator(posts_list, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:settings.POSTS_PER_PAGE]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = User.objects.get(username=username)
    author_post = Post.objects.filter(author=author).order_by('-pub_date')
    posts_numbers = author_post.count()
    paginator = Paginator(author_post, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': author,
        'author_post': author_post,
        'posts_numbers': posts_numbers,

    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):

    post = Post.objects.select_related('author', 'group').get(id=post_id)
    post_count = Post.objects.filter(author=post.author).count()
    post_list = post.author.posts.all()
    context = {
        'post_list': post_list,
        'post': post,
        'post_count': post_count,

    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):

    if request.method == 'POST':
        form = FormPost(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('posts:profile', request.user)
        return render(request, 'posts/post_create.html', {'form': form})
    form = FormPost()
    return render(request, 'posts/post_create.html', {'form': form})


'''@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = FormPost(request.POST, instance=post)
    is_edit = True
    if post.author == request.user:
        if request.method == "POST":
            form = FormPost(request.POST, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    else:
        form = FormPost(instance=post)
    return render(request, 'posts/create_post.html', {'form': form, 'is_edit': is_edit, 'post': post})'''


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    if request.method == 'GET':
        form = FormPost(instance=post)
    if request.method == 'POST':
        form = FormPost(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
        else:
            form = FormPost(instance=post)
    return render(request, 'posts/post_create.html', {'form': form, 'is_edit': is_edit, 'post': post})

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in posts %}
      <article>
        {% include 'posts/one_post.html' %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block tittle %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
    <article>
      {% include 'posts/one_post.html' %}
    </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/one_post.html
<ul>
  <li>Автор: {{ post.author.get_full_name }}</li>
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
</ul>
<p>
  {{ post.text|linebreaks }}
</p>
{% if not group %}
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
{% endif %}

yatube/templates/posts/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}Добавить Запись{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Новый пост</div>
          <div class="card-body">
            <form method="post" action="{% url 'posts:post_create' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger">*</span>
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
</textarea>
                <small id="id_text-help" class="form-text text-muted">Текст нового поста</small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">Group</label>
                <select name="group" class="form-control" id="id_group">
                  <option value="" selected>
                    ---------
                  </option>
                  <option value="1">
                    Группа: Лев Толстой – зеркало русской революции
                  </option>
                </select>
                <small id="id_group-help" class="form-text text-muted">Группа, к которой будет относиться пост</small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">Добавить</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block tittle %}<title>Пост <!-- Первые 30 букв поста --></title>{% endblock %}
{% block content %}
 
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
          <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ post.text|linebreaks }}
        </p>
      </article>
    </div>
  {% endblock %}

yatube/templates/posts/post_edit.html
{% extends "base.html" %}
{% block title %}Редактировать запись{% endblock %}
{% block content %}

  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Новый пост</div>
          <div class="card-body">
            <form method="post" action="{% url 'posts:post_edit' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger">*</span>
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
</textarea>
                <small id="id_text-help" class="form-text text-muted">Текст нового поста</small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">Group</label>
                <select name="group" class="form-control" id="id_group">
                  <option value="" selected>
                    ---------
                  </option>
                  <option value="1">
                    Группа: Лев Толстой – зеркало русской революции
                  </option>
                </select>
                <small id="id_group-help" class="form-text text-muted">Группа, к которой будет относиться пост</small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профайл пользователя {{ author.username }}{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <div class="container py-5">
      <h1>Все посты пользователя {{ author.username }}</h1>
      <h3>Всего постов: {{ posts_numbers }}</h3>
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            {% if post.author %}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            {% endif %}
          </li>
          <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        </ul>
        <p>
          {{ post.text|linebreaks }}
        </p>
        {% if post.author %}
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% endif %}
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/paginator.html' %}
  </div>
{% endblock %}